import Footer from '@/publicComponents/footer'
import { DeclaratorHeader } from '@/publicComponents/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
        <DeclaratorHeader />
        <div style={{minHeight: '67.3vh'}}>
            {children}
        </div>
        <Footer />
    </div>
  )
}
