import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { colors } from '@/publicComponents/customStyles'
import bgImg from '@assets/playgame-bg.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundImage: "url(/playgame-bg3.jpg) ", height: '100vh', margin: 0}}>{children}</body>
    </html>
  )
}
